apiVersion: v1
kind: Pod
metadata:
  name: ssl-jet-pod
  labels:
    app: ssl-jet
spec:
  containers:
  - name: container
    image: gitlab-registry.nrp-nautilus.io/jmduarte/semi-supervised-tests:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      limits:
        nvidia.com/gpu: "1"
    volumeMounts:
    - mountPath: /ssl-jet-vol
      name: ssl-jet-vol
  volumes:
    - name: ssl-jet-vol
      persistentVolumeClaim:
        claimName: ssl-jet-vol
